### PR TITLE
Match standard 'ld' "search" behavior

### PR DESCRIPTION
**Pull request by tschwinge**
@vries, agree?

No change in GCC/nvptx build behavior.

### CODE REVIEW

**Comment by vries** [comment]
> @vries, agree?
> 
> No change in GCC/nvptx build behavior.

Hi, yes that looks ok to me.

**Comment by tschwinge** [comment]
Actually, in GCC/nvptx target testing, this #38's commit 886a95faf66bf66a82fc0fe7d2a9fd9e9fec2820 "ld: Don't search for input files in '-L'directories" is generally causing linking to fail with:

```
error opening crt0.o
collect2: error: ld returned 1 exit status
compiler exited with status 1
```

I'm investigating.

**Comment by tschwinge** [comment]
Hi!

Re
<https://github.com/MentorEmbedded/nvptx-tools/pull/38#issuecomment-1320419585>:

On 2022-11-18T11:05:23-0800, I wrote:
> Actually, in GCC/nvptx target testing, this #38's commit 886a95faf66bf66a82fc0fe7d2a9fd9e9fec2820 "ld: Don't search for input files in '-L'directories" is generally causing linking to fail with:
>
> ```
> error opening crt0.o
> collect2: error: ld returned 1 exit status
> compiler exited with status 1
> ```
>
> I'm investigating.

OK to push the attached
GCC "nvptx: In 'STARTFILE_SPEC', fix 'crt0.o' for '-mmainkernel'" to all
active GCC branches?  (... instead of having to restore this "blunder"
(do "search for input files in '-L'directories") in nvptx-tools...)


Grüße
 Thomas


-----------------
Siemens Electronic Design Automation GmbH; Anschrift: Arnulfstraße 201, 80634 München; Gesellschaft mit beschränkter Haftung; Geschäftsführer: Thomas Heurung, Frank Thürauf; Sitz der Gesellschaft: München; Registergericht München, HRB 106955

**Comment by tschwinge** [comment]
On 11/19/22 00:25, Thomas Schwinge wrote:
> Hi!
> 
> Re
> <https://github.com/MentorEmbedded/nvptx-tools/pull/38#issuecomment-1320419585>:
> 
> On 2022-11-18T11:05:23-0800, I wrote:
>> Actually, in GCC/nvptx target testing, this #38's commit 886a95faf66bf66a82fc0fe7d2a9fd9e9fec2820 "ld: Don't search for input files in '-L'directories" is generally causing linking to fail with:
>>
>> ```
>> error opening crt0.o
>> collect2: error: ld returned 1 exit status
>> compiler exited with status 1
>> ```
>>
>> I'm investigating.
> 
> OK to push the attached
> GCC "nvptx: In 'STARTFILE_SPEC', fix 'crt0.o' for '-mmainkernel'" to all
> active GCC branches?  (... instead of having to restore this "blunder"
> (do "search for input files in '-L'directories") in nvptx-tools...)
> 

Hi,

yes, LGTM.

Thanks,
- Tom

> 
> Grüße
>   Thomas
> 
> 
> -----------------
> Siemens Electronic Design Automation GmbH; Anschrift: Arnulfstraße 201, 80634 München; Gesellschaft mit beschränkter Haftung; Geschäftsführer: Thomas Heurung, Frank Thürauf; Sitz der Gesellschaft: München; Registergericht München, HRB 106955

**Pull request merged**
